var user = {
"login": "zenki14",
"id": 7331768,
"avatar_url": "https://avatars.githubusercontent.com/u/7331768?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/zenki14",
"html_url": "https://github.com/zenki14",
"followers_url": "https://api.github.com/users/zenki14/followers",
"following_url": "https://api.github.com/users/zenki14/following{/other_user}",
"gists_url": "https://api.github.com/users/zenki14/gists{/gist_id}",
"starred_url": "https://api.github.com/users/zenki14/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/zenki14/subscriptions",
"organizations_url": "https://api.github.com/users/zenki14/orgs",
"repos_url": "https://api.github.com/users/zenki14/repos",
"events_url": "https://api.github.com/users/zenki14/events{/privacy}",
"received_events_url": "https://api.github.com/users/zenki14/received_events",
"type": "User",
"site_admin": false,
"name": "Dane Worsham",
"company": "",
"blog": "",
"location": "",
"email": "zenki14@gmail.com",
"hireable": false,
"bio": null,
"public_repos": 11,
"public_gists": 0,
"followers": 3,
"following": 2,
"created_at": "2014-04-17T23:20:54Z",
"updated_at": "2015-01-26T15:19:37Z"
};